<?php

namespace App\Services\Customer;

use App\Models\CropRecommendation;
use App\Models\PredictionLog;
use App\Models\User;
use App\Services\CropPredictionService;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * CropRecommendationService
 *
 * Generates recommendations by calling the Flask AI API.
 */
class CropRecommendationService
{
    public function __construct(private readonly CropPredictionService $predictionApi) {}

    /**
     * Generate crop recommendations for a user.
     *
     * @param  User   $user
     * @param  array  $input  ['nitrogen','phosphorus','potassium','ph_level','humidity','rainfall_mm','temperature']
     * @param  int|null $soilTestId
     * @return CropRecommendation
     */
    public function recommend(User $user, array $input, ?int $soilTestId = null): CropRecommendation
    {
        try {
            $apiResult = $this->predictionApi->predict($input);
            $crop = (string) ($apiResult['crop'] ?? 'unknown');
            $confidenceScore = isset($apiResult['confidence']) ? (float) $apiResult['confidence'] : null;
            $confidencePercent = $confidenceScore === null ? 0.0 : round($confidenceScore * 100, 2);

            $recommendedCrops = [[
                'crop' => $crop,
                'name' => ucfirst($crop),
                'confidence' => $confidencePercent,
                'confidence_score' => $confidenceScore,
                'notes' => 'Generated by the production Flask inference API.',
                'request_id' => $apiResult['request_id'] ?? null,
                'record_id' => $apiResult['record_id'] ?? null,
                'timestamp' => $apiResult['timestamp'] ?? null,
            ]];

            $explanation = sprintf(
                'Prediction generated by Flask API using live model inference. Request ID: %s. Record ID: %s.',
                (string) ($apiResult['request_id'] ?? 'n/a'),
                (string) ($apiResult['record_id'] ?? 'n/a')
            );

            $cropRecommendation = CropRecommendation::create([
                'user_id' => $user->id,
                'soil_test_id' => $soilTestId,
                'nitrogen' => $input['nitrogen'] ?? null,
                'phosphorus' => $input['phosphorus'] ?? null,
                'potassium' => $input['potassium'] ?? null,
                'ph_level' => $input['ph_level'] ?? null,
                'humidity' => $input['humidity'] ?? null,
                'rainfall_mm' => $input['rainfall_mm'] ?? null,
                'temperature' => $input['temperature'] ?? null,
                'recommended_crops' => $recommendedCrops,
                'explanation' => $explanation,
                'model_version' => 'flask-api-v1',
                'status' => 'completed',
            ]);

            // Log prediction to prediction_logs table for analytics
            $this->logPrediction($user->id, $cropRecommendation->id, $input, $apiResult, $crop, $confidenceScore, $confidencePercent);

            return $cropRecommendation;
        } catch (Throwable $e) {
            Log::error('Crop recommendation inference failed.', [
                'user_id' => $user->id,
                'message' => $e->getMessage(),
            ]);

            // Log failed prediction
            $this->logFailedPrediction($user->id, $input, $e);

            throw $e;
        }
    }

    /**
     * Log successful prediction to the database for analytics.
     */
    private function logPrediction(
        int $userId,
        int $cropRecommendationId,
        array $input,
        array $apiResult,
        string $crop,
        ?float $confidenceScore,
        float $confidencePercent
    ): void {
        try {
            PredictionLog::create([
                'user_id' => $userId,
                'crop_recommendation_id' => $cropRecommendationId,
                'nitrogen' => $input['nitrogen'] ?? null,
                'phosphorus' => $input['phosphorus'] ?? null,
                'potassium' => $input['potassium'] ?? null,
                'temperature' => $input['temperature'] ?? null,
                'humidity' => $input['humidity'] ?? null,
                'ph_level' => $input['ph_level'] ?? null,
                'rainfall_mm' => $input['rainfall_mm'] ?? null,
                'predicted_crop' => strtolower($crop),
                'confidence_score' => $confidenceScore,
                'confidence_percent' => (int) $confidencePercent,
                'request_id' => $apiResult['request_id'] ?? null,
                'record_id' => $apiResult['record_id'] ?? null,
                'model_version' => $apiResult['model_version'] ?? 'flask-api-v1',
                'model_name' => $apiResult['model_name'] ?? 'RandomForest',
                'status' => 'completed',
                'predicted_at' => now(),
            ]);
        } catch (Throwable $e) {
            Log::warning('Failed to log prediction to database.', [
                'user_id' => $userId,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Log failed prediction attempts.
     */
    private function logFailedPrediction(int $userId, array $input, Throwable $error): void
    {
        try {
            PredictionLog::create([
                'user_id' => $userId,
                'nitrogen' => $input['nitrogen'] ?? null,
                'phosphorus' => $input['phosphorus'] ?? null,
                'potassium' => $input['potassium'] ?? null,
                'temperature' => $input['temperature'] ?? null,
                'humidity' => $input['humidity'] ?? null,
                'ph_level' => $input['ph_level'] ?? null,
                'rainfall_mm' => $input['rainfall_mm'] ?? null,
                'predicted_crop' => 'unknown',
                'confidence_score' => 0,
                'confidence_percent' => 0,
                'model_version' => 'flask-api-v1',
                'model_name' => 'RandomForest',
                'status' => 'failed',
                'error_details' => [
                    'message' => $error->getMessage(),
                    'code' => $error->getCode(),
                    'file' => $error->getFile(),
                    'line' => $error->getLine(),
                ],
                'predicted_at' => now(),
            ]);
        } catch (Throwable $e) {
            Log::warning('Failed to log error prediction to database.', [
                'user_id' => $userId,
                'error' => $e->getMessage(),
            ]);
        }
    }
}


