<?php

namespace App\Services\Customer;

use App\Models\CropRecommendation;
use App\Services\CropPredictionService;
use App\Models\User;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * CropRecommendationService
 *
 * Generates recommendations by calling the Flask AI API.
 */
class CropRecommendationService
{
    public function __construct(private readonly CropPredictionService $predictionApi) {}

    /**
     * Generate crop recommendations for a user.
     *
     * @param  User   $user
     * @param  array  $input  ['nitrogen','phosphorus','potassium','ph_level','humidity','rainfall_mm','temperature']
     * @param  int|null $soilTestId
     * @return CropRecommendation
     */
    public function recommend(User $user, array $input, ?int $soilTestId = null): CropRecommendation
    {
        try {
            $apiResult = $this->predictionApi->predict($input);
            $crop = (string) ($apiResult['crop'] ?? 'unknown');
            $confidenceScore = isset($apiResult['confidence']) ? (float) $apiResult['confidence'] : null;
            $confidencePercent = $confidenceScore === null ? 0.0 : round($confidenceScore * 100, 2);

            $recommendedCrops = [[
                'crop' => $crop,
                'name' => ucfirst($crop),
                'confidence' => $confidencePercent,
                'confidence_score' => $confidenceScore,
                'notes' => 'Generated by the production Flask inference API.',
                'request_id' => $apiResult['request_id'] ?? null,
                'record_id' => $apiResult['record_id'] ?? null,
                'timestamp' => $apiResult['timestamp'] ?? null,
            ]];

            $explanation = sprintf(
                'Prediction generated by Flask API using live model inference. Request ID: %s. Record ID: %s.',
                (string) ($apiResult['request_id'] ?? 'n/a'),
                (string) ($apiResult['record_id'] ?? 'n/a')
            );

            return CropRecommendation::create([
                'user_id' => $user->id,
                'soil_test_id' => $soilTestId,
                'nitrogen' => $input['nitrogen'] ?? null,
                'phosphorus' => $input['phosphorus'] ?? null,
                'potassium' => $input['potassium'] ?? null,
                'ph_level' => $input['ph_level'] ?? null,
                'humidity' => $input['humidity'] ?? null,
                'rainfall_mm' => $input['rainfall_mm'] ?? null,
                'temperature' => $input['temperature'] ?? null,
                'recommended_crops' => $recommendedCrops,
                'explanation' => $explanation,
                'model_version' => 'flask-api-v1',
                'status' => 'completed',
            ]);
        } catch (Throwable $e) {
            Log::error('Crop recommendation inference failed.', [
                'user_id' => $user->id,
                'message' => $e->getMessage(),
            ]);

            throw $e;
        }
    }
}


