<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VendorsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Vendor user IDs start after the 2 admin users → IDs 3–12
        $vendorUsers = DB::table('users')->where('role', 'vendor')->pluck('id')->toArray();
        $zones       = DB::table('zones')->pluck('id', 'zone_name');
        $cats        = DB::table('categories')->pluck('id', 'name');

        $data = [
            [
                'author_id'       => $vendorUsers[0],
                'zone'            => 'Lahore',
                'category'        => 'Seeds',
                'title'           => 'Punjab Seeds Centre',
                'description'     => 'Authorized dealer of Fauji Fertilizer & PARC certified seeds. Stocks all major hybrid varieties.',
                'address'         => 'Shop 14, Akbari Mandi, Lahore',
                'latitude'        => 31.5730,
                'longitude'       => 74.3510,
                'phone'           => '+92-42-37650123',
                'delivery_fee'    => 150.00,
                'min_order'       => 500.00,
                'prep_time'       => 30,
                'commission'      => 8.00,
                'open'            => '08:00', 'close' => '20:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[1],
                'zone'            => 'Faisalabad',
                'category'        => 'Fertilizers',
                'title'           => 'Sona Fertilizer Store',
                'description'     => 'Wholesale & retail of Urea, DAP, MOP and micronutrient fertilizers. Certified RAZA distributor.',
                'address'         => 'Ghanta Ghar Road, Faisalabad',
                'latitude'        => 31.4160,
                'longitude'       => 73.0822,
                'phone'           => '+92-41-2640456',
                'delivery_fee'    => 200.00,
                'min_order'       => 1000.00,
                'prep_time'       => 45,
                'commission'      => 6.00,
                'open'            => '07:30', 'close' => '19:30',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[2],
                'zone'            => 'Multan',
                'category'        => 'Pesticides',
                'title'           => 'Al-Rehman Agro Supplies',
                'description'     => 'Complete range of Syngenta, Bayer and FMC pesticides. Expert agronomist on staff.',
                'address'         => 'Vehari Road, Multan',
                'latitude'        => 30.1600,
                'longitude'       => 71.5250,
                'phone'           => '+92-61-4510789',
                'delivery_fee'    => 180.00,
                'min_order'       => 800.00,
                'prep_time'       => 40,
                'commission'      => 7.50,
                'open'            => '08:00', 'close' => '18:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[3],
                'zone'            => 'Bahawalpur',
                'category'        => 'Insecticides',
                'title'           => 'Kisaan Agri Mart',
                'description'     => 'Insecticide, nematicide and acaricide solutions for cotton and wheat. Authorised Bayer dealer.',
                'address'         => 'Model Town, Bahawalpur',
                'latitude'        => 29.3980,
                'longitude'       => 71.6870,
                'phone'           => '+92-62-2880234',
                'delivery_fee'    => 220.00,
                'min_order'       => 1200.00,
                'prep_time'       => 50,
                'commission'      => 9.00,
                'open'            => '07:00', 'close' => '19:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[4],
                'zone'            => 'Gujranwala',
                'category'        => 'Seeds',
                'title'           => 'Green Land Seeds',
                'description'     => 'High-yield paddy, wheat and maize seed varieties. ISO 9001 certified warehouse.',
                'address'         => 'GT Road, Gujranwala',
                'latitude'        => 32.1900,
                'longitude'       => 74.1950,
                'phone'           => '+92-55-3821010',
                'delivery_fee'    => 160.00,
                'min_order'       => 600.00,
                'prep_time'       => 35,
                'commission'      => 7.00,
                'open'            => '08:00', 'close' => '20:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[5],
                'zone'            => 'Sahiwal',
                'category'        => 'Fertilizers',
                'title'           => 'Ittehad Fertilizers',
                'description'     => 'SOP, potash and liquid nutrient solutions. Serving sugarcane and cotton farmers.',
                'address'         => 'Chichawatni Road, Sahiwal',
                'latitude'        => 30.6720,
                'longitude'       => 73.1100,
                'phone'           => '+92-40-4226780',
                'delivery_fee'    => 175.00,
                'min_order'       => 900.00,
                'prep_time'       => 40,
                'commission'      => 6.50,
                'open'            => '08:30', 'close' => '18:30',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[6],
                'zone'            => 'Peshawar',
                'category'        => 'Pesticides',
                'title'           => 'KPK Agro Solutions',
                'description'     => 'Weed killers, fungicides and tobacco-crop pesticides. Certified DRAP-registered stock.',
                'address'         => 'Hayatabad Phase 4, Peshawar',
                'latitude'        => 34.0200,
                'longitude'       => 71.5900,
                'phone'           => '+92-91-5842011',
                'delivery_fee'    => 200.00,
                'min_order'       => 700.00,
                'prep_time'       => 35,
                'commission'      => 8.50,
                'open'            => '09:00', 'close' => '19:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[7],
                'zone'            => 'Karachi',
                'category'        => 'Bio Pesticides',
                'title'           => 'Biocare Agri Pakistan',
                'description'     => 'Organic bio-pesticide importer. Bacillus thuringiensis, neem extracts and pheromone traps.',
                'address'         => 'SITE Area, Sindh Industrial Estate, Karachi',
                'latitude'        => 24.8700,
                'longitude'       => 67.0100,
                'phone'           => '+92-21-36340567',
                'delivery_fee'    => 250.00,
                'min_order'       => 1500.00,
                'prep_time'       => 60,
                'commission'      => 10.00,
                'open'            => '09:00', 'close' => '18:00',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[8],
                'zone'            => 'Sukkur',
                'category'        => 'Herbicides',
                'title'           => 'Sindh Crop Care',
                'description'     => 'Herbicide solutions for rice, wheat and sugarcane. Serving Sukkur and Khairpur districts.',
                'address'         => 'Military Road, Sukkur',
                'latitude'        => 27.7080,
                'longitude'       => 68.8600,
                'phone'           => '+92-71-5612300',
                'delivery_fee'    => 190.00,
                'min_order'       => 850.00,
                'prep_time'       => 45,
                'commission'      => 7.00,
                'open'            => '08:00', 'close' => '17:30',
                'is_approved'     => true,
            ],
            [
                'author_id'       => $vendorUsers[9],
                'zone'            => 'Quetta',
                'category'        => 'Fungicides',
                'title'           => 'Balochistan Crop Protect',
                'description'     => 'Fungicide & bactericide solutions for apple, apricot and grape orchards.',
                'address'         => 'Jinnah Road, Quetta',
                'latitude'        => 30.1820,
                'longitude'       => 67.0100,
                'phone'           => '+92-81-2838222',
                'delivery_fee'    => 230.00,
                'min_order'       => 1000.00,
                'prep_time'       => 55,
                'commission'      => 9.50,
                'open'            => '08:00', 'close' => '18:00',
                'is_approved'     => true,
            ],
        ];

        foreach ($data as $d) {
            DB::table('vendors')->insert([
                'author_id'       => $d['author_id'],
                'zone_id'         => $zones[$d['zone']] ?? null,
                'category_id'     => $cats[$d['category']] ?? null,
                'title'           => $d['title'],
                'description'     => $d['description'],
                'address'         => $d['address'],
                'latitude'        => $d['latitude'],
                'longitude'       => $d['longitude'],
                'phone'           => $d['phone'],
                'rating'          => round(rand(35, 50) / 10, 1),
                'review_count'    => rand(10, 120),
                'is_active'       => true,
                'is_approved'     => $d['is_approved'],
                'open_time'       => $d['open'],
                'close_time'      => $d['close'],
                'delivery_fee'    => $d['delivery_fee'],
                'min_order_amount'=> $d['min_order'],
                'preparation_time'=> $d['prep_time'],
                'commission_rate' => $d['commission'],
                'created_at'      => $now,
                'updated_at'      => $now,
            ]);
        }

        $this->command->info('VendorsSeeder: ' . DB::table('vendors')->count() . ' vendors inserted.');
    }
}
